Adding httpd-worker apache process on SLES
The apache2 process on SLES might be 'httpd-worker'. Otherwise
while running monasca-setup, the error is:
     ERROR: Apache process does not exist.

Change-Id: I27c757b9c3c3b93db7b3edd8e576147e94c32a4a
(cherry picked from commit f3410a4475d0ef29168e9f366a204619a5e0d220)