self.name doesn't exist in Rate and Counter object
Saw error message in collector log showing:
AttributeError: 'Rate' object has no attribute 'name'

In the new base metric class init function, variable name
got passed into self.metric. That's why self.name doesn't
exist anymore.

Change-Id: Idfd2fe5d257332327449e2766544dd36d8a003c1