Update old python string format
Currently kubernetes.py debug statement prints utilizes old
string format, thus leading to
TypeError: not all arguments converted during string formatting

Fixed the string format function in debug statements.

Change-Id: I4ef602cf356082ed3d5e8a924336f38a84179430
Task: 14309
Story: 2001857
Signed-off-by: Jui Chandwaskar <jchandwaskar@op5.com>