Fix error logs in prometheus w/o prometheus annotations.
when pods have no prometheus annotation, and the prometheus
plugin is activated, for each pod that is found an error log
is generated indicating that:
File "/usr/local/lib/python2.7/site-packages/monasca_agent/common/../collector/checks_d/prometheus.py", line 276, in _get_prometheus_endpoint
    endpoints.append("{}/{}".format(ports[pod_index], prometheus_endpoint))
 TypeError: list indices must be integers, not str

The problem comes from the fact that the there are no endpoints
defined in the annotations, as well as that the reference on
line 276 should use an integer.

Story: 2001609
Task: 6570
Change-Id: I4ba0d41a6ff56885750894be2dc87ac1ee9168d0
(cherry picked from commit 4b11f413c2185bbdf037fc381d01910c008a0b31)