Detect httpd on openSUSE/SLES
The apache2 process name on openSUSE might be 'httpd-prefork'. Otherwise
while running monasca-setup, the error is:

      ERROR: Apache process does not exist.

Change-Id: I11a2220283d27d3d65248287b90c7f4455d11e9a
(cherry picked from commit 56ff5b04da2eca9ff33ec8098ecb9e40e2b761b0)