Fix kafka_consumer detection plugin for localhost
If no host.name is specified in /etc/kafka/server.properties, the
kafka_consumer detection plugin is supposed to use 'localhost' for
its kafka connect string, but this is not working, causing this
output when running monasca-setup:

INFO:   Kafka found listening on :9092
ERROR: Unable to connect to kafka broker at :9092

I also altered the output a bit because defaulting to localhost is
not really an error.

Change-Id: I6cf03a39c1f40cd12a31e31922af73b3216ee582