Fix AttributeError: 'virDomain' object has no attribute 'id'
When checking 'libvirt' instance and inspecting disk info,
monasca_agent collector complains errors "AttributeError: 'virDomain'
object has no attribute 'id'". Because 'instance' has no attribute 'id',
so 'instance.id' will lead to errors. We can use 'instance.ID()' to
get an instance uuid.

Change-Id: Ife95c2a976a99bb73e71a3764fa1c4f5d26cc36e
Story: 2000987
Task: 4164
Closes-Bug:#1682354